config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'

  get '/login', to: 'session#new'
  get '/signup', to: 'visitors#new'
  
  post '/login', to: 'session#create'
  post '/signup', to: 'visitors#create'
  
  
 
  resources :visitors 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 },
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end
  
  def create
    @visitor = Visitor.find_by(email: params[:session][:email].downcase)
    if @visitor && @visitor.authenticate(params[:session][:password])
      flash[:success] = 'Loged in! Welcome!'
      redirect_to @visitor
    else
      flash.now[:danger] = 'Login failed!'
      render 'new'
    end
  end
  
  def destroy
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

def show
    @visitor = Visitor.find(params[:id])
end

def destroy
if @visitor = Visitor.find(params[:id])
  @visitor.destroy
  respond_to do |format| 
    format.html { redirect_to visitors_path } 
    format.xml { head :ok } 
  end
 end
end

def index
  @visitors = Visitor.all
 # raise @visitor.inspect
end


def new
  @visitor = Visitor.new
end

def create
  @visitor = Visitor.new(secure_params)
  if @visitor.save
      flash[:sucess] = "toll"
      redirect_to @visitor
    else
      render 'new'
  end
end

def secure_params
  params.require(:visitor).permit(:name, :email, :password, :password_confirmation)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "vendor/modernizr" %>

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    
    <h1>Header Project 1</h1>


    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

    
    

    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "sample app", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Sing up", signup_path %></li>
            <li><%= link_to "Login", login_path %></li>
            <li><%= link_to "Visitors", visitors_path %></li>
          </ul>
        </nav>
      </div>
    </header>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    
   
   <%= render 'layouts/header' %>
  
  </head>

  <body>

    <%= yield %>

  </body>
        <%= debug(params) if Rails.env.development? %>

</html>

app/views/session/new.html.erb
<h1>Session#new</h1>

<div class="row">
 <div class="col-md-6 col-md-offset-3">
<%= form_for(:session, url: login_path) do |f| %>
  <%= f.label 'eMail' %>
  <%= f.email_field :email, class: 'form-control' %>
  <%= f.label 'Password' %>
  <%= f.password_field :password, class: 'form-control' %>
   <%= f.submit "Log in", class: "btn btn-primary" %>
<% end %>
</div>
</div>

app/views/shared/_error_messages.html.erb
<% if @visitor.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@visitor.errors.count, "error") %>.
    </div>
    <ul>
    <% @visitor.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>
 <%= link_to 'Signup', signup_path %> 

app/views/visitors/index.html.erb
<% provide(:title, 'Visitors') %>
<h3>Visitors index project1</h3>

<h1>All users</h1>

<ul>
  <% @visitors.each do |visitor| %>
  <li>
     <div style="float: left"> <%= link_to visitor.name, visitor %> &nbsp; &nbsp; </div>  
     <div> <%= button_to "delete", visitor, :method=>:delete, :class=>:destroy %>    </div>
  </li>
  <% end %>
</ul>

app/views/visitors/new.html.erb
<% provide(:title, 'Sign up') %>
<h3>Visitor project1</h3>

<div class="row">
 <div class="col-md-6 col-md-offset-3">
<%= form_for(@visitor, url: signup_path) do |f| %>
  <%= render 'shared/error_messages' %>
  <%= f.label 'Name' %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= f.label 'eMail' %>
  <%= f.email_field :email, class: 'form-control' %>
  <%= f.label 'Password' %>
  <%= f.password_field :password, class: 'form-control' %>
  <%= f.label 'Password confirmation' %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
   <%= f.submit "Sign up", class: "btn btn-primary" %>
<% end %>
</div>
</div>

<h1></h1>
<%= link_to 'Already user? - Login', login_path %>

app/views/visitors/show.html.erb
<% provide(:title, @visitor.name) %>
<h3>Visitor show project1</h3>
<div>
<label>Name: <%= @visitor.name %></label><br/>
<label>E-Mail: <%= @visitor.email %></label><br/>
<label>Password_Digest: <%= @visitor.password_digest %></label><br/>
</div>